window.APP_DATA = {
  "source": {
    "workbook": "Gestion Campo - Base de Datos - Omar Jacob.xlsx",
    "generatedAt": "2026-05-18T00:00:00.000Z"
  },
  "lots": [
    {
      "id": "LOT-001",
      "name": "Hasenkamp 1",
      "farm": "Hasenkamp",
      "hectares": 133,
      "campaign": "2026/27",
      "crop": "Maiz",
      "variety": "",
      "previousCrop": "Trigo/Soja",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-002",
      "name": "Hasenkamp 4",
      "farm": "Hasenkamp",
      "hectares": 30,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-003",
      "name": "Hasenkamp 6",
      "farm": "Hasenkamp",
      "hectares": 35,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-004",
      "name": "Hasenkamp 9",
      "farm": "Hasenkamp",
      "hectares": 41,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-005",
      "name": "Hasenkamp 13",
      "farm": "Hasenkamp",
      "hectares": 77,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-006",
      "name": "Hasenkamp 17",
      "farm": "Hasenkamp",
      "hectares": 17,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-007",
      "name": "Hasenkamp 19",
      "farm": "Hasenkamp",
      "hectares": 19,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-008",
      "name": "Hasenkamp 23",
      "farm": "Hasenkamp",
      "hectares": 23,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-009",
      "name": "Villaguay 1",
      "farm": "Villaguay",
      "hectares": 59,
      "campaign": "2026/27",
      "crop": "Soja 1ra",
      "variety": "",
      "previousCrop": "Maiz",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-010",
      "name": "Villaguay 2",
      "farm": "Villaguay",
      "hectares": 50,
      "campaign": "2026/27",
      "crop": "Maiz",
      "variety": "",
      "previousCrop": "Trigo/Soja",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-011",
      "name": "Villaguay 3",
      "farm": "Villaguay",
      "hectares": 48,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-012",
      "name": "Villaguay 4",
      "farm": "Villaguay",
      "hectares": 42,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-013",
      "name": "Villaguay Bruschis Tolosa",
      "farm": "Villaguay",
      "hectares": 19,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-014",
      "name": "Villaguay Bruschis 23",
      "farm": "Villaguay",
      "hectares": 23,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-015",
      "name": "Villaguay Bruschis Monte",
      "farm": "Villaguay",
      "hectares": 18,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-016",
      "name": "Villaguay 5 Alto",
      "farm": "Villaguay",
      "hectares": 32,
      "campaign": "2026/27",
      "crop": "Maiz",
      "variety": "",
      "previousCrop": "Trigo/Soja",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-017",
      "name": "Villaguay 5 Bajo",
      "farm": "Villaguay",
      "hectares": 39,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-018",
      "name": "Villaguay 6",
      "farm": "Villaguay",
      "hectares": 34,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-019",
      "name": "Villaguay 7",
      "farm": "Villaguay",
      "hectares": 21,
      "campaign": "2026/27",
      "crop": "Trigo/Soja",
      "variety": "",
      "previousCrop": "Soja 1ra",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-020",
      "name": "Villaguay 25",
      "farm": "Villaguay",
      "hectares": 23,
      "campaign": "2026/27",
      "crop": "Maiz",
      "variety": "",
      "previousCrop": "Trigo/Soja",
      "environment": "",
      "notes": ""
    },
    {
      "id": "LOT-021",
      "name": "Villaguay Villagra",
      "farm": "Villaguay",
      "hectares": 16,
      "campaign": "2026/27",
      "crop": "Maiz",
      "variety": "",
      "previousCrop": "Trigo/Soja",
      "environment": "",
      "notes": ""
    }
  ],
  "products": [],
  "orders": [],
  "monitors": [],
  "applications": [],
  "closures": [
    {
      "id": "ROT-LOT-001-2025-26-01",
      "campaignGroupId": "ROT-LOT-001-2025-26",
      "lotId": "LOT-001",
      "lotName": "Hasenkamp 1",
      "campaign": "2025/26",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 133,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-001-2025-26-02",
      "campaignGroupId": "ROT-LOT-001-2025-26",
      "lotId": "LOT-001",
      "lotName": "Hasenkamp 1",
      "campaign": "2025/26",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 133,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-001-2024-25-01",
      "campaignGroupId": "ROT-LOT-001-2024-25",
      "lotId": "LOT-001",
      "lotName": "Hasenkamp 1",
      "campaign": "2024/25",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 133,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-002-2025-26-01",
      "campaignGroupId": "ROT-LOT-002-2025-26",
      "lotId": "LOT-002",
      "lotName": "Hasenkamp 4",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 30,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-002-2024-25-01",
      "campaignGroupId": "ROT-LOT-002-2024-25",
      "lotId": "LOT-002",
      "lotName": "Hasenkamp 4",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 30,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-002-2024-25-02",
      "campaignGroupId": "ROT-LOT-002-2024-25",
      "lotId": "LOT-002",
      "lotName": "Hasenkamp 4",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 30,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-003-2025-26-01",
      "campaignGroupId": "ROT-LOT-003-2025-26",
      "lotId": "LOT-003",
      "lotName": "Hasenkamp 6",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 35,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-003-2024-25-01",
      "campaignGroupId": "ROT-LOT-003-2024-25",
      "lotId": "LOT-003",
      "lotName": "Hasenkamp 6",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 35,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-003-2024-25-02",
      "campaignGroupId": "ROT-LOT-003-2024-25",
      "lotId": "LOT-003",
      "lotName": "Hasenkamp 6",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 35,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-004-2025-26-01",
      "campaignGroupId": "ROT-LOT-004-2025-26",
      "lotId": "LOT-004",
      "lotName": "Hasenkamp 9",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 41,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-004-2024-25-01",
      "campaignGroupId": "ROT-LOT-004-2024-25",
      "lotId": "LOT-004",
      "lotName": "Hasenkamp 9",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 41,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-005-2025-26-01",
      "campaignGroupId": "ROT-LOT-005-2025-26",
      "lotId": "LOT-005",
      "lotName": "Hasenkamp 13",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 77,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-005-2024-25-01",
      "campaignGroupId": "ROT-LOT-005-2024-25",
      "lotId": "LOT-005",
      "lotName": "Hasenkamp 13",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 77,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-006-2025-26-01",
      "campaignGroupId": "ROT-LOT-006-2025-26",
      "lotId": "LOT-006",
      "lotName": "Hasenkamp 17",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 17,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-006-2024-25-01",
      "campaignGroupId": "ROT-LOT-006-2024-25",
      "lotId": "LOT-006",
      "lotName": "Hasenkamp 17",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 17,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-006-2024-25-02",
      "campaignGroupId": "ROT-LOT-006-2024-25",
      "lotId": "LOT-006",
      "lotName": "Hasenkamp 17",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 17,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-007-2025-26-01",
      "campaignGroupId": "ROT-LOT-007-2025-26",
      "lotId": "LOT-007",
      "lotName": "Hasenkamp 19",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-007-2024-25-01",
      "campaignGroupId": "ROT-LOT-007-2024-25",
      "lotId": "LOT-007",
      "lotName": "Hasenkamp 19",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-007-2024-25-02",
      "campaignGroupId": "ROT-LOT-007-2024-25",
      "lotId": "LOT-007",
      "lotName": "Hasenkamp 19",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-008-2025-26-01",
      "campaignGroupId": "ROT-LOT-008-2025-26",
      "lotId": "LOT-008",
      "lotName": "Hasenkamp 23",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-008-2024-25-01",
      "campaignGroupId": "ROT-LOT-008-2024-25",
      "lotId": "LOT-008",
      "lotName": "Hasenkamp 23",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-008-2024-25-02",
      "campaignGroupId": "ROT-LOT-008-2024-25",
      "lotId": "LOT-008",
      "lotName": "Hasenkamp 23",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-009-2025-26-01",
      "campaignGroupId": "ROT-LOT-009-2025-26",
      "lotId": "LOT-009",
      "lotName": "Villaguay 1",
      "campaign": "2025/26",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 59,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-009-2024-25-01",
      "campaignGroupId": "ROT-LOT-009-2024-25",
      "lotId": "LOT-009",
      "lotName": "Villaguay 1",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 59,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-009-2024-25-02",
      "campaignGroupId": "ROT-LOT-009-2024-25",
      "lotId": "LOT-009",
      "lotName": "Villaguay 1",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 59,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-010-2025-26-01",
      "campaignGroupId": "ROT-LOT-010-2025-26",
      "lotId": "LOT-010",
      "lotName": "Villaguay 2",
      "campaign": "2025/26",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 50,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-010-2025-26-02",
      "campaignGroupId": "ROT-LOT-010-2025-26",
      "lotId": "LOT-010",
      "lotName": "Villaguay 2",
      "campaign": "2025/26",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 50,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-010-2024-25-01",
      "campaignGroupId": "ROT-LOT-010-2024-25",
      "lotId": "LOT-010",
      "lotName": "Villaguay 2",
      "campaign": "2024/25",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 50,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-011-2025-26-01",
      "campaignGroupId": "ROT-LOT-011-2025-26",
      "lotId": "LOT-011",
      "lotName": "Villaguay 3",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 48,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-011-2024-25-01",
      "campaignGroupId": "ROT-LOT-011-2024-25",
      "lotId": "LOT-011",
      "lotName": "Villaguay 3",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 48,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-012-2025-26-01",
      "campaignGroupId": "ROT-LOT-012-2025-26",
      "lotId": "LOT-012",
      "lotName": "Villaguay 4",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 42,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-012-2024-25-01",
      "campaignGroupId": "ROT-LOT-012-2024-25",
      "lotId": "LOT-012",
      "lotName": "Villaguay 4",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 42,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-013-2025-26-01",
      "campaignGroupId": "ROT-LOT-013-2025-26",
      "lotId": "LOT-013",
      "lotName": "Villaguay Bruschis Tolosa",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-013-2024-25-01",
      "campaignGroupId": "ROT-LOT-013-2024-25",
      "lotId": "LOT-013",
      "lotName": "Villaguay Bruschis Tolosa",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-013-2024-25-02",
      "campaignGroupId": "ROT-LOT-013-2024-25",
      "lotId": "LOT-013",
      "lotName": "Villaguay Bruschis Tolosa",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 19,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-014-2025-26-01",
      "campaignGroupId": "ROT-LOT-014-2025-26",
      "lotId": "LOT-014",
      "lotName": "Villaguay Bruschis 23",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-014-2024-25-01",
      "campaignGroupId": "ROT-LOT-014-2024-25",
      "lotId": "LOT-014",
      "lotName": "Villaguay Bruschis 23",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-014-2024-25-02",
      "campaignGroupId": "ROT-LOT-014-2024-25",
      "lotId": "LOT-014",
      "lotName": "Villaguay Bruschis 23",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-015-2025-26-01",
      "campaignGroupId": "ROT-LOT-015-2025-26",
      "lotId": "LOT-015",
      "lotName": "Villaguay Bruschis Monte",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 18,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-015-2024-25-01",
      "campaignGroupId": "ROT-LOT-015-2024-25",
      "lotId": "LOT-015",
      "lotName": "Villaguay Bruschis Monte",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 18,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-015-2024-25-02",
      "campaignGroupId": "ROT-LOT-015-2024-25",
      "lotId": "LOT-015",
      "lotName": "Villaguay Bruschis Monte",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 18,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-016-2025-26-01",
      "campaignGroupId": "ROT-LOT-016-2025-26",
      "lotId": "LOT-016",
      "lotName": "Villaguay 5 Alto",
      "campaign": "2025/26",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 32,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-016-2025-26-02",
      "campaignGroupId": "ROT-LOT-016-2025-26",
      "lotId": "LOT-016",
      "lotName": "Villaguay 5 Alto",
      "campaign": "2025/26",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 32,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-016-2024-25-01",
      "campaignGroupId": "ROT-LOT-016-2024-25",
      "lotId": "LOT-016",
      "lotName": "Villaguay 5 Alto",
      "campaign": "2024/25",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 32,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-017-2025-26-01",
      "campaignGroupId": "ROT-LOT-017-2025-26",
      "lotId": "LOT-017",
      "lotName": "Villaguay 5 Bajo",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 39,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-017-2024-25-01",
      "campaignGroupId": "ROT-LOT-017-2024-25",
      "lotId": "LOT-017",
      "lotName": "Villaguay 5 Bajo",
      "campaign": "2024/25",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 39,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-017-2024-25-02",
      "campaignGroupId": "ROT-LOT-017-2024-25",
      "lotId": "LOT-017",
      "lotName": "Villaguay 5 Bajo",
      "campaign": "2024/25",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 39,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-018-2025-26-01",
      "campaignGroupId": "ROT-LOT-018-2025-26",
      "lotId": "LOT-018",
      "lotName": "Villaguay 6",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 34,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-018-2024-25-01",
      "campaignGroupId": "ROT-LOT-018-2024-25",
      "lotId": "LOT-018",
      "lotName": "Villaguay 6",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 34,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-019-2025-26-01",
      "campaignGroupId": "ROT-LOT-019-2025-26",
      "lotId": "LOT-019",
      "lotName": "Villaguay 7",
      "campaign": "2025/26",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 21,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-019-2024-25-01",
      "campaignGroupId": "ROT-LOT-019-2024-25",
      "lotId": "LOT-019",
      "lotName": "Villaguay 7",
      "campaign": "2024/25",
      "crop": "Maiz",
      "variety": "",
      "enso": "",
      "hectares": 21,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-020-2025-26-01",
      "campaignGroupId": "ROT-LOT-020-2025-26",
      "lotId": "LOT-020",
      "lotName": "Villaguay 25",
      "campaign": "2025/26",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-020-2025-26-02",
      "campaignGroupId": "ROT-LOT-020-2025-26",
      "lotId": "LOT-020",
      "lotName": "Villaguay 25",
      "campaign": "2025/26",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-020-2024-25-01",
      "campaignGroupId": "ROT-LOT-020-2024-25",
      "lotId": "LOT-020",
      "lotName": "Villaguay 25",
      "campaign": "2024/25",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 23,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-021-2025-26-01",
      "campaignGroupId": "ROT-LOT-021-2025-26",
      "lotId": "LOT-021",
      "lotName": "Villaguay Villagra",
      "campaign": "2025/26",
      "crop": "Trigo",
      "variety": "",
      "enso": "",
      "hectares": 16,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-021-2025-26-02",
      "campaignGroupId": "ROT-LOT-021-2025-26",
      "lotId": "LOT-021",
      "lotName": "Villaguay Villagra",
      "campaign": "2025/26",
      "crop": "Soja",
      "variety": "",
      "enso": "",
      "hectares": 16,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    },
    {
      "id": "ROT-LOT-021-2024-25-01",
      "campaignGroupId": "ROT-LOT-021-2024-25",
      "lotId": "LOT-021",
      "lotName": "Villaguay Villagra",
      "campaign": "2024/25",
      "crop": "Soja 1ra",
      "variety": "",
      "enso": "",
      "hectares": 16,
      "kgHarvested": "",
      "priceTon": "",
      "otherCosts": "",
      "applicationCosts": "",
      "income": "",
      "grossMargin": ""
    }
  ],
  "mapPolygons": []
};
